// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PRN232.LMS.Repositories.Data;

#nullable disable

namespace PRN232.LMS.Repositories.Migrations
{
    [DbContext(typeof(LmsdbContext))]
    [Migration("20260528061855_AddDb")]
    partial class AddDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PRN232.LMS.Repositories.Entities.Course", b =>
                {
                    b.Property<int>("Courseid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Courseid"));

                    b.Property<string>("Coursecode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Coursename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Semesterid")
                        .HasColumnType("integer");

                    b.HasKey("Courseid");

                    b.HasIndex("Semesterid");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("PRN232.LMS.Repositories.Entities.Enrollment", b =>
                {
                    b.Property<int>("Enrollmentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Enrollmentid"));

                    b.Property<int>("Courseid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Enrolldate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Studentid")
                        .HasColumnType("integer");

                    b.HasKey("Enrollmentid");

                    b.HasIndex("Courseid");

                    b.HasIndex("Studentid");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("PRN232.LMS.Repositories.Entities.Semester", b =>
                {
                    b.Property<int>("Semesterid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Semesterid"));

                    b.Property<DateTime>("Enddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Semestername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Startdate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Semesterid");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("PRN232.LMS.Repositories.Entities.Student", b =>
                {
                    b.Property<int>("Studentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Studentid"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Dateofbirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Studentcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Studentid");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("PRN232.LMS.Repositories.Entities.Subject", b =>
                {
                    b.Property<int>("Subjectid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Subjectid"));

                    b.Property<int>("Credit")
                        .HasColumnType("integer");

                    b.Property<string>("Subjectcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subjectname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Subjectid");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("PRN232.LMS.Repositories.Entities.Course", b =>
                {
                    b.HasOne("PRN232.LMS.Repositories.Entities.Semester", "Semester")
                        .WithMany("Courses")
                        .HasForeignKey("Semesterid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("PRN232.LMS.Repositories.Entities.Enrollment", b =>
                {
                    b.HasOne("PRN232.LMS.Repositories.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("Courseid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRN232.LMS.Repositories.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("Studentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PRN232.LMS.Repositories.Entities.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("PRN232.LMS.Repositories.Entities.Semester", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("PRN232.LMS.Repositories.Entities.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
